version: '3'
services:

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - hex-network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: "1000:1000"
        container_name: app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app:rw
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - hex-network
networks:
    hex-network:
        driver: bridge